In [1]:
# load in required packages
import pandas as pd
import geopandas as gpd
import numpy as np
from citymob import import_csv_w_wkt_to_gdf
crs0=3035

In [2]:
# this are the new scores, calculated in December
city='Berlin'
fp='../../MSCA_data/access-score-23-11-15/access-score-'  + city + '.gpkg'
gdf=gpd.read_file(fp)
gdf['score_spatiotemporal_min']=gdf['score_spatiotemporal']/60
gdf=gdf.loc[:,['geocode','score_spatiotemporal_min']]
gdf

    geocode  score_spatiotemporal_min
0     10115                 94.283052
1     10117                105.260238
2     10119                 95.796198
3     10178                149.809166
4     10179                 92.844364
..      ...                       ...
186   14193                  7.306712
187   14195                 33.942893
188   14197                 41.877449
189   14199                 30.550585
190   16548                  1.052598

[191 rows x 2 columns]

In [4]:
gdf['score_spatiotemporal_min'].describe()

count    191.000000
mean      42.542915
std       27.312209
min        1.052598
25%       23.800328
50%       37.773305
75%       57.616058
max      151.243467
Name: score_spatiotemporal_min, dtype: float64

In [8]:
cities_all=['Berlin','Dresden','Düsseldorf','Frankfurt am Main','Kassel','Leipzig','Magdeburg','Potsdam','Clermont','Dijon','Lille','Lyon','Montpellier','Nantes','Nimes','Paris','Toulouse','Madrid','Wien']
for city in cities_all:
    fp='../../MSCA_data/access-score-23-11-15/access-score-'  + city + '.gpkg'
    gdf=gpd.read_file(fp)
    gdf['score_spatiotemporal_min']=gdf['score_spatiotemporal']/60
    gdf=gdf.loc[:,['geocode','score_spatiotemporal_min']]
    gdf['geocode']=gdf['geocode'].astype(str)
    gdf.to_csv('../outputs/transit_access/' + city + '.csv',index=False)

In [74]:
# these are the new postcodes for Clermont
fp1='../source/GTFS/postcodes_gpkg_all/' + city + '_postcodes.gpkg'
gdf1=gpd.read_file(fp1)
gdf1

    geocode                                           geometry
0       101  POLYGON ((3918596.884 2528851.593, 3918587.992...
1       102  POLYGON ((3918887.647 2529568.648, 3918906.476...
2       103  POLYGON ((3919368.104 2530299.797, 3919366.294...
3       104  POLYGON ((3918991.202 2531926.330, 3919073.857...
4       105  POLYGON ((3918860.630 2531387.484, 3918885.722...
..      ...                                                ...
175  249001  POLYGON ((3911952.226 2511680.724, 3911998.396...
176  249002  POLYGON ((3909072.081 2510456.646, 3909092.795...
177  249351  POLYGON ((3912212.563 2511292.627, 3912301.279...
178  249451  POLYGON ((3911952.226 2511680.724, 3911979.455...
179     250  POLYGON ((3912890.637 2513294.078, 3912918.067...

[180 rows x 2 columns]

In [75]:
fpd='../outputs/density_geounits/' + city + '_pop_density_mixres.csv'
gdfd=import_csv_w_wkt_to_gdf(fpd,crs0,gc='geocode')
#gdfd.rename(columns={'geo_unit':'geocode'},inplace=True)
gdfd

,geocode,geometry,area,Population,Density,source
0,101,"POLYGON ((3918596.884 2528851.593, 3918587.992...",1.920276,10763.349946,5605.107093,large_units
1,102,"POLYGON ((3918887.647 2529568.648, 3918906.476...",0.540942,10454.032327,19325.590313,large_units
2,103,"POLYGON ((3919368.104 2530299.797, 3919366.294...",0.925875,9812.939556,10598.556730,large_units
3,104,"POLYGON ((3918991.202 2531926.330, 3919073.857...",0.523416,10345.883971,19766.063990,large_units
4,105,"POLYGON ((3918860.630 2531387.484, 3918885.722...",0.999327,19308.306051,19321.311928,large_units
...,...,...,...,...,...,...
175,249001,"POLYGON ((3911952.226 2511680.724, 3911998.396...",0.744618,2264.655305,3041.364497,small_units_agg
176,249002,"POLYGON ((3909072.081 2510456.646, 3909092.795...",8.109650,3513.495916,433.248783,small_units_agg
177,249351,"POLYGON ((3912212.563 2511292.627, 3912301.279...",0.525358,3246.524663,6179.648429,small_units_agg
178,249451,"POLYGON ((3911952.226 2511680.724, 3911979.455...",0.745171,681.483824,914.533364,small_units_agg
179,250,"POLYGON ((3912890.637 2513294.078, 3912918.067...",7.322768,10203.896781,1393.447959,large_units

In [76]:
all(gdfd['geocode']==gdf1['geocode'])

True

In [22]:
# this is the new score, calculated for Clermont
fp='../outputs/access-score-French-cities-Nov-23/access-score-' + city + '.gpkg'
gdf=gpd.read_file(fp)
gdf.head(15)
gdf

,geocode,score_spatiotemporal,geometry
0,1,1.949276e+03,"POLYGON ((3826267.797 2298407.891, 3826267.555..."
1,2,2.334747e+03,"POLYGON ((3826590.478 2297856.256, 3826583.278..."
2,3,1.935309e+03,"POLYGON ((3826930.241 2297304.961, 3826912.017..."
3,4,7.104937e+02,"POLYGON ((3825278.992 2297219.192, 3825277.783..."
4,5,1.227421e+03,"POLYGON ((3825876.699 2298729.980, 3825835.060..."
...,...,...,...
82,54001,2.313314e-05,"POLYGON ((3838470.529 2303609.598, 3838486.638..."
83,54003,2.697887e-04,"POLYGON ((3837051.641 2303535.592, 3837063.947..."
84,54005,1.376679e-02,"POLYGON ((3837340.795 2301225.824, 3837327.094..."
85,54010,2.100179e-08,"POLYGON ((3840205.386 2303380.306, 3840213.508..."
86,57,1.166725e+00,"POLYGON ((3828678.889 2304122.798, 3828671.305..."

In [27]:
all(gdf['geocode']==gdf2['geocode'])

False

In [24]:
# this is the old score, calculated for Clermont
fp2='../outputs/transit-access-eu/access-score-' + city + '.gpkg'
gdf2=gpd.read_file(fp2)
gdf2.head(10)
gdf2

,geocode,score_centrality,score_centrality_norm,score_spatiotemporal,score_spatial,geometry
0,1,0.744015,6.756695e+02,2613.604613,573.982248,"POLYGON ((3826267.797 2298407.891, 3826267.555..."
1,2,0.895312,8.279280e+02,3050.452109,611.451532,"POLYGON ((3826590.478 2297856.256, 3826583.278..."
2,3,0.826461,7.626581e+02,2876.236008,699.117949,"POLYGON ((3826930.241 2297304.961, 3826912.017..."
3,4,0.330915,2.623165e+02,1319.556094,396.261297,"POLYGON ((3825278.992 2297219.192, 3825277.783..."
4,5,0.474647,4.057510e+02,1795.722525,469.078098,"POLYGON ((3825876.699 2298729.980, 3825835.060..."
...,...,...,...,...,...,...
82,54001,0.013700,1.600012e-42,88.454535,105.214231,"POLYGON ((3838470.529 2303609.598, 3838486.638..."
83,54003,0.018939,6.021713e-37,123.158972,155.638418,"POLYGON ((3837051.641 2303535.592, 3837063.947..."
84,54005,0.012736,1.369678e-20,84.029658,114.278418,"POLYGON ((3837340.795 2301225.824, 3837327.094..."
85,54010,0.007535,4.839854e-58,55.996215,65.501917,"POLYGON ((3840205.386 2303380.306, 3840213.508..."
86,57,0.022564,3.057126e+00,107.865553,95.280986,"POLYGON ((3828678.889 2304122.798, 3828671.305..."

In [15]:
gdf2['score_spatiotemporal']/gdf['score_spatiotemporal']

0     3.628764e+00
1     3.214792e+00
2     3.090421e+00
3     4.295108e+00
4     7.184879e+00
          ...
62    2.137371e+02
63    5.936794e+02
64    3.531567e+08
65    1.291892e+01
66    1.481269e+04
Name: score_spatiotemporal, Length: 67, dtype: float64

In [14]:
gdf.head(25)

,geocode,score_spatiotemporal,geometry
0,101,955.231539,"POLYGON ((3783719.764 2543031.559, 3783710.822..."
1,102,728.045712,"POLYGON ((3783022.462 2542248.810, 3783013.837..."
2,103,597.828443,"POLYGON ((3783868.647 2540929.610, 3783833.156..."
3,104,915.134774,"POLYGON ((3783999.209 2542580.556, 3784005.876..."
4,105001,271.014782,"POLYGON ((3785404.798 2543017.625, 3785388.610..."
5,105002,157.234164,"POLYGON ((3784346.811 2543026.727, 3784352.102..."
6,105003,189.681429,"POLYGON ((3785849.720 2542406.474, 3785788.835..."
7,105008,71.559424,"POLYGON ((3785844.532 2543323.700, 3785828.454..."
8,105011,496.049784,"POLYGON ((3786339.002 2541938.488, 3786348.125..."
9,105012,130.398627,"POLYGON ((3788299.615 2540467.582, 3788234.231..."
10,106,708.362147,"POLYGON ((3785032.568 2543541.868, 3785052.421..."
11,107,523.927017,"POLYGON ((3786223.108 2545961.098, 3786115.052..."
12,108,113.009479,"POLYGON ((3782295.287 2543845.976, 3782290.160..."
13,109001,205.555134,"POLYGON ((3782101.741 2543367.671, 3782104.421..."
14,109002,202.331148,"POLYGON ((3782196.733 2543118.969, 3782135.067..."
15,109003,393.386452,"POLYGON ((3782532.050 2542367.068, 3782578.105..."
16,109004,118.121203,"POLYGON ((3782081.246 2542018.751, 3781770.061..."
17,109005,103.167400,"POLYGON ((3781034.243 2542459.105, 3781063.200..."
18,109006,144.590456,"POLYGON ((3780464.134 2543858.913, 3780458.952..."
19,109007,45.598253,"POLYGON ((3781072.526 2544492.419, 3781059.057..."
20,109008,250.879767,"POLYGON ((3782428.615 2543247.902, 3782253.344..."
21,109009,13.226195,"POLYGON ((3781336.443 2541923.283, 3781328.477..."
22,110,102.294006,"POLYGON ((3783510.131 2539370.173, 3783453.338..."
23,111001,0.038280,"POLYGON ((3780385.003 2538815.604, 3780402.529..."
24,111002,4.668617,"POLYGON ((3781659.601 2541691.163, 3781604.385..."

In [9]:
fp2='../outputs/transit-access-eu/access-score-' + city + '.gpkg'
gdf2=gpd.read_file(fp2)
gdf2.head(15)

,geocode,score_centrality,score_centrality_norm,score_spatiotemporal,score_spatial,geometry
0,101,1.138172,1298.795699,3466.309628,1535.191291,"POLYGON ((3783719.764 2543031.559, 3783710.822..."
1,102,0.735539,789.611651,2340.515419,1071.649985,"POLYGON ((3783022.462 2542248.810, 3783013.837..."
2,103,0.557396,577.436995,1847.541557,778.299251,"POLYGON ((3783868.647 2540929.610, 3783833.156..."
3,104,1.299256,1497.423745,3930.602663,1845.623677,"POLYGON ((3783999.209 2542580.556, 3784005.876..."
4,105001,0.581502,552.597954,1947.208299,1078.633832,"POLYGON ((3785404.798 2543017.625, 3785388.610..."
5,105002,0.518977,482.233999,1735.885082,993.998675,"POLYGON ((3784346.811 2543026.727, 3784352.102..."
6,105003,0.456539,438.695053,1531.645524,816.608272,"POLYGON ((3785849.720 2542406.474, 3785788.835..."
7,105008,0.139574,94.785322,526.554103,336.994639,"POLYGON ((3785844.532 2543323.700, 3785828.454..."
8,105011,0.368507,327.091967,1344.915400,541.613734,"POLYGON ((3786339.002 2541938.488, 3786348.125..."
9,105012,0.146701,118.274143,557.447690,277.661671,"POLYGON ((3788299.615 2540467.582, 3788234.231..."
10,106,0.584847,617.200206,1910.170444,904.783686,"POLYGON ((3785032.568 2543541.868, 3785052.421..."
11,107,0.274922,240.669523,1053.082950,448.118245,"POLYGON ((3786223.108 2545961.098, 3786115.052..."
12,108,0.204742,151.278570,755.210899,514.976164,"POLYGON ((3782295.287 2543845.976, 3782290.160..."
13,109001,0.400463,339.107995,1414.116156,794.842155,"POLYGON ((3782101.741 2543367.671, 3782104.421..."
14,109002,0.357704,297.556593,1258.278590,676.644407,"POLYGON ((3782196.733 2543118.969, 3782135.067..."